[test]
# Enable coverage by default
coverage = true

# Set coverage thresholds - tests will fail if coverage falls below these
coverageThreshold = { lines = 0.95, functions = 0.95, statements = 0.95 }

# Skip test files themselves from coverage calculations
coverageSkipTestFiles = true

# Generate both text (console) and lcov (for CI/editors) reports
coverageReporter = ["text", "lcov"]

# Directory for coverage reports
coverageDir = "coverage"

# Ignore specific patterns from coverage
coveragePathIgnorePatterns = [
  "**/*.test.ts",
  "**/*.spec.ts",
  "**/fixtures/**",
  "**/generateFixtureData.ts"
]
